#!/usr/bin/env python3
"""Generate lib/features/certificate/certificate_catalog.dart

Source of truth: tool/certificate-types.json（12306 证件类型目录，
参考 D:/Codes/CR_wiki/证件类型.json）。

Usage: python tool/gen_certificate_catalog.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tool" / "certificate-types.json"
OUT = ROOT / "lib" / "features" / "certificate" / "certificate_catalog.dart"

# JSON 外补充的 ICAO/常用旅行证件签发地（JSON 仅含"外国人护照"国别清单）
EXTRA_ISO3 = {
    "CHN": "中国/China",
    "HKG": "中国香港/Hong Kong, China",
    "MAC": "中国澳门/Macao, China",
    "TWN": "中国台湾/Taiwan, China",
}


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    types = data["idTypes"]

    lines = [
        "// lib/features/certificate/certificate_catalog.dart",
        "//",
        "// GENERATED by tool/gen_certificate_catalog.py — 勿手改。",
        "// 来源：tool/certificate-types.json（12306 购票证件目录 + 外国护照签发国 ISO3 清单）。",
        "library;",
        "",
        "/// 单一证件类型（12306 两字母代码体系）",
        "class CertTypeSpec {",
        "  const CertTypeSpec(this.code, this.name,",
        "      {this.printCode, this.printName, this.remark});",
        "  final String code;",
        "  final String name;",
        "  final String? printCode;",
        "  final String? printName;",
        "  final String? remark;",
        "}",
        "",
        "/// 全量证件类型目录（12306）",
        "const Map<String, CertTypeSpec> kCertCatalog = {",
    ]
    codes: list[str] = []
    for t in types:
        code = t["code"]
        codes.append(code)
        args = [dart_str(code), dart_str(t["name"])]
        named = []
        if "print_code" in t:
            named.append(f"printCode: {dart_str(t['print_code'])}")
        if "print_name" in t:
            named.append(f"printName: {dart_str(t['print_name'])}")
        if "remake" in t:
            named.append(f"remark: {dart_str(t['remake'])}")
        if named:
            args.append(", ".join(named))
        prefix = f"  {dart_str(code)}: CertTypeSpec("
        if named:
            lines.append(prefix + args[0] + ", " + args[1] + ", " + args[2] + "),")
        else:
            lines.append(prefix + args[0] + ", " + args[1] + "),")

    lines += [
        "};",
        "",
        "/// 目录顺序（UI 下拉用）",
        "const List<String> kCertCodes = [",
        *[f"  {dart_str(c)}," for c in codes],
        "];",
        "",
        "/// ICAO 3 字母国别码 → 名称（外国人护照签发国 + 中国/港澳台）",
        "const Map<String, String> kIso3Names = {",
    ]

    iso3: dict[str, str] = dict(EXTRA_ISO3)
    for t in types:
        if t["code"] == "WH" and "country" in t:
            for c in t["country"]:
                iso3.setdefault(c["code"], c["name"])
    for code in sorted(iso3):
        lines.append(f"  {dart_str(code)}: {dart_str(iso3[code])},")
    lines += ["};", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"OK {OUT.relative_to(ROOT)}: {len(codes)} types, {len(iso3)} iso3")


if __name__ == "__main__":
    main()
